config/routes.rb
Rails.application.routes.draw do
  resources :jobs

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	def index
		@jobs = Job.all
    end
    
    def new
      @job = Job.new
    end
    
    def create
      p "in the create method!"
     Job.create(job_params)
     p 'job'
     redirect_to jobs_path
    end

    def edit
   	 @job = Job.find(params[:id])
    end

    def update
   	 @job = Job.find(params[:id])
   	 @job.update_attributes(job_params)
   	 redirect_to jobs_path
    end
    def destroy
   	 @job = Job.find(params[:id])
   	 @job.destroy
   	 redirect_to jobs_path
    end

   private

   def job_params
   	 puts "in job_params"
   	 puts params.require(:job).permit(:title, :description)
     params.require(:job).permit(:title, :description)
   end

   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%=form_for @job do |f| %>
  <div class="form-group">
  <div>
    <%= f.label :title %>
  </div>
  <div>
    <%= f.text_field :title %>
  </div>
  </div>
  <div class="form-group">
  <div>
    <%= f.label :description %>
  </div>
  <div>
    <%= f.text_area :description, size: '60x6' %>
  </div>
  
  

  </div>
  <div>
   <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit Posting</h1>
<%= render "form" %>

app/views/jobs/index.html.erb
<h1 class="hero">RailsBridgeCorp Open Jobs</h1>
<% @jobs.each do |job| %>
<div class="container">
	<h3 class="job-title"><%= job.title %></h3>
    <p class="job-descript" ><%= job.description %></p>
    

 <div class="btn-action">
    <button class="btn btn-default"><%=link_to "Edit Posting", edit_job_path(job)%></button>
    <button  class="btn btn-warning"><%= link_to 'Delete Posting', job, method: :delete %></button>
 </div>
</div>
<% end %>

app/views/jobs/new.html.erb
<h1>Add a job</h1>
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="bg-success">
<div class="row">
<header class='clearfix'>
<div class="container-header">
  <div class='left-nav'>
    <ul>
      <li><%=link_to 'Home', jobs_path %></li>
    </ul>
   </div>
   <div class='right-nav'>
     <ul>
       <li><%=link_to 'Add Job', new_job_path %></li>
     </ul>
   </div>
  </div>
 </header>
<div class='content'>
  <%= yield %>
</div>
</div>
</body>
</html>